BASE_TASK_CONFIG_PATH: /home/orbit/桌面/Nav-2025/GES_vlnce/VLN_CE/habitat_extensions/config/vlnce_task_GES_r2r.yaml
EVAL:
    IDENTIFICATION: r2r
    SPLIT: val_unseen
    # any num greater than the actual episode count evals every episode